language: r
cache: packages
latex: false

warnings_are_errors: false
r_check_args: --no-manual

r:
  - release
  
services:
  - mysql
  
before_install:
  - gunzip ./inst/testdata/world-utf8.sql.gz --stdout | mysql -u root --default-character-set=utf8 
  
env:
  global:
    - _R_CHECK_TESTS_NLINES_=0